openapi: 3.0.0
info:
  title: API Онлайн-магазина
  version: 1.0.0
  description: API для управления товарами и заказами в онлайн-магазине.
  contact:
    name: Поддержка Онлайн-магазина
    email: support@example.com

servers:
  - url: https://api.OnlineStore.com/v1

paths:
  /products:
    get:
      summary: Получить список всех товаров
      responses:
        '200':
          description: Список товаров
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

    post:
      summary: Добавить новый товар
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewProduct'
      responses:
        '201':
          description: Товар создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'

  /products/{productId}:
    parameters:
      - name: productId
        in: path
        required: true
        description: ID товара
        schema:
          type: string

    get:
      summary: Получить товар по ID
      responses:
        '200':
          description: Детали товара
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Товар не найден

    put:
      summary: Обновить товар
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProduct'
      responses:
        '200':
          description: Товар обновлен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Товар не найден

    delete:
      summary: Удалить товар
      responses:
        '204':
          description: Товар удален
        '404':
          description: Товар не найден

  /orders:
    post:
      summary: Создать новый заказ
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewOrder'
      responses:
        '201':
          description: Заказ создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          example: "12345"
        name:
          type: string
          example: "Новый товар"
        description:
          type: string
          example: "Описание товара"
        price:
          type: number
          format: float
          example: 29.99
        stock:
          type: integer
          example: 100

    NewProduct:
      type: object
      properties:
        name:
          type: string
          example: "Новый товар"
        description:
          type: string
          example: "Описание товара"
        price:
          type: number
          format: float
          example: 29.99
        stock:
          type: integer
          example: 100

    UpdateProduct:
      type: object
      properties:
        name:
          type: string
          example: "Обновленный товар"
        description:
          type: string
          example: "Обновленное описание товара"
        price:
          type: number
          format: float
          example: 39.99
        stock:
          type: integer
          example: 50

    NewOrder:
      type: object
      properties:
        productId:
          type: string
          example: "12345"
        quantity:
          type: integer
          example: 2

Order:
      type: object
      properties:
        id:
          type: string
          example: "order123"
        productId:
          type: string
          example: "12345"
        quantity:
          type: integer
          example: 2
        status:
          type: string
          example: "Создан"
